baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

# 主导航菜单
name="首页"
url="/"
weight="1"
[[menu.main]]
name="博文"
url="/posts"
weight="2"
[[menu.main]]
name="关于"
url="/about"
weight="3"
